version: '3'
services:
    nginx:
        image: docker-01:5000/panw_nginx:1
        restart: always
        ports:
            - 80:80
        depends_on: 
            - backend
            - frontend
            - pma
    frontend:
        image: docker-01:5000/panw_frontend:1
        restart: always
        # ports:
        #     - 4200:4200
        volumes:
            - /app/node_modules
            - ./frontend:/app
    backend:
        image: docker-01:5000/panw_backend:1
        restart: always
        deploy:
            mode: replicated
            replicas: 2
        volumes:
            - ./backend:/app
        depends_on: 
            - db
        # ports:
        #     - 8080:8080
        environment: 
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_HOST=${MYSQL_HOST}
    db:
        image: docker-01:5000/panw_db:1
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        # ports:
        #     - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    pma:
        image: docker-01:5000/panw_pma:1
        restart: always
        # ports:
            # - 8081:80
        environment: 
            - PMA_HOST=db
            - HIDE_PHP_VERSION=1
            - PMA_ABSOLUTE_URI=${URL}/pma

