version: '3'
services:
    registry:
        image: prom/prometheus
        restart: always
        ports:
             - 9090:9090
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml